# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

project_name: kuroryuu

includes:
  - from_url:
      url: charmbracelet/meta/main/notarize.yaml

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
  license: "FSL-1.1-MIT"
  homepage: "https://kuroryuu.com"
  description: "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal."
  full_description: "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal."
  maintainers:
    - "maintainer@kuroryuu.com"
    - "cli@kuroryuu.com

nightly:
  publish_release: true
  keep_single_release: true
  version_template: "{{ incminor .Version }}-nightly"

snapshot:
  version_template: "0.0.0-{{ .Timestamp }}"

before:
  hooks:
    - go mod tidy
    - rm -rf completions
    - mkdir completions
    - rm -rf manpages
    - mkdir manpages
    - sh -c 'go run . completion bash >./completions/kuroryuu.bash'
    - sh -c 'go run . completion zsh >./completions/kuroryuu.zsh'
    - sh -c 'go run . completion fish >./completions/kuroryuu.fish'
    - sh -c 'go run . man | gzip -c >./manpages/kuroryuu.1.gz'

# gomod:
#   proxy: true

builds:
  - env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=greenteagc
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
      - android
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "7"
    ignore:
      - goos: android
        goarch: amd64
      - goos: android
        goarch: arm
      - goos: android
        goarch: "386"
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X github.com/ahostbr/crush/internal/version.Version={{.Version}}
    flags:
      - -trimpath

archives:
  - name_template: >-
      kuroryuu_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm}}v{{ . }}{{ end }}
    wrap_in_directory: true
    files:
      - README*
      - LICENSE*
      - manpages/*
      - completions/*
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

aur_sources:
  - private_key: "{{ .Env.AUR_KEY }}"
    disable: "{{ with .Prerelease }}true{{ end }}"
    git_url: "ssh://aur@aur.archlinux.org/kuroryuu.git"
    commit_author:
      name: "Kuroryuu"
      email: "cli@kuroryuu.com"
    makedepends:
      - go
      - git
    prepare: |-
      go mod download
    build: |-
      mkdir completions
      mkdir manpages
      export CGO_CPPFLAGS="${CPPFLAGS}"
      export CGO_CFLAGS="${CFLAGS}"
      export CGO_CXXFLAGS="${CXXFLAGS}"
      export CGO_LDFLAGS="${LDFLAGS}"
      export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
      go build -ldflags="-w -s -buildid='' -linkmode=external -X github.com/ahostbr/crush/internal/version.Version=v${pkgver}" .
      ./kuroryuu completion bash >./completions/kuroryuu.bash
      ./kuroryuu completion zsh >./completions/kuroryuu.zsh
      ./kuroryuu completion fish >./completions/kuroryuu.fish
      ./kuroryuu man | gzip -c >./manpages/kuroryuu.1.gz
    package: |-
      # bin
      install -Dm755 "./kuroryuu" "${pkgdir}/usr/bin/kuroryuu"
      # license
      mkdir -p "${pkgdir}/usr/share/licenses/kuroryuu/"
      install -Dm644 ./LICENSE* "${pkgdir}/usr/share/licenses/kuroryuu/"
      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/kuroryuu.bash" "${pkgdir}/usr/share/bash-completion/completions/kuroryuu"
      install -Dm644 "./completions/kuroryuu.zsh" "${pkgdir}/usr/share/zsh/site-functions/_kuroryuu"
      install -Dm644 "./completions/kuroryuu.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/kuroryuu.fish"
      # man pages
      install -Dm644 "./manpages/kuroryuu.1.gz" "${pkgdir}/usr/share/man/man1/kuroryuu.1.gz"
      # readme
      mkdir -pv "${pkgdir}/usr/share/doc/kuroryuu/"
      install -Dm644 README* "${pkgdir}/usr/share/doc/kuroryuu/"

aurs:
  - private_key: "{{ .Env.AUR_KEY }}"
    disable: "{{ with .Prerelease }}true{{ end }}"
    git_url: "ssh://aur@aur.archlinux.org/kuroryuu-bin.git"
    commit_author:
      name: "Kuroryuu"
      email: "cli@kuroryuu.com"
    provides:
      - kuroryuu
    conflicts:
      - kuroryuu
    package: |-
      case "$CARCH" in
        aarch64)
          cd "${srcdir}/kuroryuu_${pkgver}_Linux_arm64"
          ;;
        *)
          cd "${srcdir}/kuroryuu_${pkgver}_Linux_${CARCH}"
          ;;
      esac
      # bin
      install -Dm755 "./kuroryuu" "${pkgdir}/usr/bin/kuroryuu"
      # license
      mkdir -p "${pkgdir}/usr/share/licenses/kuroryuu/"
      install -Dm644 ./LICENSE* "${pkgdir}/usr/share/licenses/kuroryuu/"
      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/kuroryuu.bash" "${pkgdir}/usr/share/bash-completion/completions/kuroryuu"
      install -Dm644 "./completions/kuroryuu.zsh" "${pkgdir}/usr/share/zsh/site-functions/_kuroryuu"
      install -Dm644 "./completions/kuroryuu.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/kuroryuu.fish"
      # man pages
      install -Dm644 "./manpages/kuroryuu.1.gz" "${pkgdir}/usr/share/man/man1/kuroryuu.1.gz"
      # readme
      mkdir -pv "${pkgdir}/usr/share/doc/kuroryuu/"
      install -Dm644 README* "${pkgdir}/usr/share/doc/kuroryuu/"

furies:
  - disable: "{{ if (or .Prerelease .IsNightly) }}true{{ end }}"
    account: "{{ with .Env.FURY_TOKEN }}charmcli{{ else }}{{ end }}"
    secret_name: FURY_TOKEN

brews:
  - repository:
      owner: ahostbr
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    skip_upload: "{{ with .Prerelease }}true{{ end }}"
    commit_author:
      name: "Kuroryuu"
      email: "cli@kuroryuu.com"
    goarm: 7
    extra_install: |-
      bash_completion.install "completions/{{ .ProjectName }}.bash" => "{{ .ProjectName }}"
      zsh_completion.install "completions/{{ .ProjectName }}.zsh" => "_{{ .ProjectName }}"
      fish_completion.install "completions/{{ .ProjectName }}.fish"
      man1.install "manpages/{{ .ProjectName }}.1.gz"

scoops:
  - repository:
      owner: ahostbr
      name: scoop-bucket
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    skip_upload: "{{ with .Prerelease }}true{{ end }}"
    commit_author:
      name: "Kuroryuu"
      email: "cli@kuroryuu.com"

npms:
  - name: "@ahostbr/kuroryuu"
    repository: "git+https://github.com/ahostbr/kuroryuu.git"
    bugs: https://github.com/ahostbr/crush/issues
    access: public
    disable: "{{ with .Prerelease }}true{{ end }}"

nfpms:
  - formats:
      - apk
      - deb
      - rpm
      - archlinux
      - termux.deb
    file_name_template: "{{ .ConventionalFileName }}"
    contents:
      - src: ./completions/kuroryuu.bash
        dst: '{{ if eq .Format "termux.deb" }}/data/data/com.termux/files/usr{{ end }}/etc/bash_completion.d/kuroryuu'
      - src: ./completions/kuroryuu.fish
        dst: '{{ if eq .Format "termux.deb" }}/data/data/com.termux/files{{ end }}/usr/share/fish/vendor_completions.d/kuroryuu.fish'
      - src: ./completions/kuroryuu.zsh
        dst: '{{ if eq .Format "termux.deb" }}/data/data/com.termux/files{{ end }}/usr/share/zsh/site-functions/_kuroryuu'
      - src: ./manpages/kuroryuu.1.gz
        dst: '{{ if eq .Format "termux.deb" }}/data/data/com.termux/files{{ end }}/usr/share/man/man1/kuroryuu.1.gz'
    rpm:
      signature:
        key_file: '{{ if ne (index .Env "GPG_KEY_PATH") "" }}{{ .Env.GPG_KEY_PATH }}{{ else }}{{ end }}'
    deb:
      signature:
        key_file: '{{ if ne (index .Env "GPG_KEY_PATH") "" }}{{ .Env.GPG_KEY_PATH }}{{ else }}{{ end }}'

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

nix:
  - repository:
      owner: "ahostbr"
      name: nur
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "Kuroryuu"
      email: "cli@kuroryuu.com"
    license: agpl3Only
    formatter: nixfmt
    skip_upload: "{{ with .Prerelease }}true{{ end }}"
    extra_install: |-
      installManPage ./manpages/kuroryuu.1.gz
      installShellCompletion ./completions/*

winget:
  - publisher: ahostbr
    copyright: ahostbr
    publisher_url: https://kuroryuu.com
    release_notes_url: "https://github.com/ahostbr/crush/releases/tag/{{.Tag}}"
    license_url: https://github.com/ahostbr/crush/blob/main/LICENSE.md
    skip_upload: "{{ with .Prerelease }}true{{ end }}"
    commit_author:
      name: "Kuroryuu"
      email: "cli@kuroryuu.com"
    repository:
      owner: "ahostbr"
      name: winget-pkgs
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      branch: "kuroryuu-{{.Version}}"
      pull_request:
        enabled: true
        draft: false
        check_boxes: true
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

changelog:
  sort: asc
  disable: "{{ .IsNightly }}"
  use: github
  filters:
    exclude:
      - "^(build|ci): "
      - "^chore: auto-update generated files$"
      - "^chore: docs$"
      - "^chore: schema update$"
      - "^chore: schema$"
      - "^chore: typo$"
      - "^chore: update schema$"
      - "^chore: update$"
      - "^chore\\(legal\\): "
      - "^chore\\(deps\\): "
      - "^docs: update$"
      - "^test:"
      - "^test\\("
      - "^v\\d.*"
      - "merge conflict"
      - "merge conflict"
      - Merge branch
      - Merge pull request
      - Merge remote-tracking branch
      - go mod tidy
      - "^wip "
      - "^wip:"
  groups:
    - title: "Deps"
      regexp: "^.*\\(deps\\)*:+.*$"
      order: 300
    - title: "New!"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Fixed"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Docs"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: "Other stuff"
      order: 9999

release:
  prerelease: auto
  footer:
    from_url:
      url: https://raw.githubusercontent.com/charmbracelet/meta/main/footer.md
